apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    "api-approved.kubernetes.io": "unapproved"
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
    - all
    - svcat
  versions:
  - name: v1beta1
    additionalPrinterColumns:
    - name: Class
      type: string
      jsonPath: .status.userSpecifiedClassName
    - name: Plan
      type: string
      jsonPath: .status.userSpecifiedPlanName
    - name: Status
      type: string
      jsonPath: .status.lastConditionState
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema'
        properties:
          apiVersion:
            description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.apiVersion'
            type: string
          kind:
            description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.kind'
            type: string
          metadata:
            type: object
          spec:
            description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec'
            properties:
              clusterServiceClassExternalID:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServiceClassExternalID'
                type: string
              clusterServiceClassExternalName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServiceClassExternalName'
                type: string
              clusterServiceClassName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServiceClassName'
                type: string
              clusterServiceClassRef:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServiceClassRef'
                properties:
                  name:
                    description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServiceClassRef.properties.name'
                    type: string
                type: object
              clusterServicePlanExternalID:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServicePlanExternalID'
                type: string
              clusterServicePlanExternalName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServicePlanExternalName'
                type: string
              clusterServicePlanName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServicePlanName'
                type: string
              clusterServicePlanRef:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServicePlanRef'
                properties:
                  name:
                    description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.clusterServicePlanRef.properties.name'
                    type: string
                type: object
              externalID:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.externalID'
                type: string
              parameters:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  x-kubernetes-int-or-string: true
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parameters'
                type: object
              parametersFrom:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom'
                items:
                  description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items'
                  properties:
                    secretKeyRef:
                      description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef'
                      properties:
                        key:
                          description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef.properties.key'
                          type: string
                        name:
                          description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef.properties.name'
                          type: string
                      required:
                      - key
                      - name
                      type: object
                  type: object
                type: array
              serviceClassExternalID:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.serviceClassExternalID'
                type: string
              serviceClassExternalName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.serviceClassExternalName'
                type: string
              serviceClassName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.serviceClassName'
                type: string
              serviceClassRef:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.serviceClassRef'
                properties:
                  name:
                    description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.serviceClassRef.properties.name'
                    type: string
                type: object
              servicePlanExternalID:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servicePlanExternalID'
                type: string
              servicePlanExternalName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servicePlanExternalName'
                type: string
              servicePlanName:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servicePlanName'
                type: string
              servicePlanRef:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servicePlanRef'
                properties:
                  name:
                    description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servicePlanRef.properties.name'
                    type: string
                type: object
              updateRequests:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.updateRequests'
                format: int64
                type: integer
              userInfo:
                description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.userInfo'
                properties:
                  extra:
                    additionalProperties:
                      description: '%serviceinstance.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.userInfo.properties.extra.additionalProperties'
                      items:
                        type: string
                      type: array
                    type: object
                  groups:
                    items:
                      type: string
                    type: array
                  uid:
                    type: string
                  username:
                    type: string
                required:
                - uid
                - username
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}