apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicebindings.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    "api-approved.kubernetes.io": "unapproved"
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: servicebindings
    singular: servicebinding
    kind: ServiceBinding
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
    - all
    - svcat
  versions:
  - name: v1beta1
    additionalPrinterColumns:
    - name: Service-Instance
      type: string
      jsonPath: .spec.instanceRef.name
    - name: Secret-Name
      type: string
      jsonPath: .spec.secretName
    - name: Status
      type: string
      jsonPath: .status.lastConditionState
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema'
        properties:
          apiVersion:
            description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.apiVersion'
            type: string
          kind:
            description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.kind'
            type: string
          metadata:
            type: object
          spec:
            description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec'
            properties:
              instanceRef:
                description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.instanceRef'
                properties:
                  name:
                    description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.instanceRef.properties.name'
                    type: string
                type: object
              parameters:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  x-kubernetes-int-or-string: true
                description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parameters'
                type: object
              parametersFrom:
                description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom'
                items:
                  description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items'
                  properties:
                    secretKeyRef:
                      description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef'
                      properties:
                        key:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef.properties.key'
                          type: string
                        name:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.parametersFrom.items.properties.secretKeyRef.properties.name'
                          type: string
                      required:
                      - key
                      - name
                      type: object
                  type: object
                type: array
              secretName:
                description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretName'
                type: string
              secretTransforms:
                description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms'
                items:
                  description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items'
                  properties:
                    addKey:
                      description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKey'
                      properties:
                        jsonPathExpression:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKey.properties.jsonPathExpression'
                          type: string
                        key:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKey.properties.key'
                          type: string
                        stringValue:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKey.properties.stringValue'
                          type: string
                        value:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKey.properties.value'
                          format: byte
                          type: string
                      required:
                      - jsonPathExpression
                      - key
                      - stringValue
                      - value
                      type: object
                    addKeysFrom:
                      description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKeysFrom'
                      properties:
                        secretRef:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKeysFrom.properties.secretRef'
                          properties:
                            name:
                              description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKeysFrom.properties.secretRef.properties.name'
                              type: string
                            namespace:
                              description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.addKeysFrom.properties.secretRef.properties.namespace'
                              type: string
                          type: object
                      type: object
                    removeKey:
                      description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.removeKey'
                      properties:
                        key:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.removeKey.properties.key'
                          type: string
                      required:
                      - key
                      type: object
                    renameKey:
                      description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.renameKey'
                      properties:
                        from:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.renameKey.properties.from'
                          type: string
                        to:
                          description: '%servicebinding.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.secretTransforms.items.properties.renameKey.properties.to'
                          type: string
                      required:
                      - from
                      - to
                      type: object
                  type: object
                type: array
            required:
            - instanceRef
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}